spring:
  profiles:
    active: default 
---
spring:
  profiles: default
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate.ddl-auto: create-drop
logging:
  level:
    com.kalah: INFO
